// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in ArabiyaPath user's profile: name, email, preferred dialect, and admin flag.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roleRow }] = await Promise.all([
      supabase.from("profiles").select("first_name,last_name,email,preferred_dialect_id,email_verified,marketing_consent").eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId).eq("role", "admin").maybeSingle()
    ]);
    const result = {
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email ?? null,
      first_name: profile?.first_name ?? null,
      last_name: profile?.last_name ?? null,
      preferred_dialect_id: profile?.preferred_dialect_id ?? null,
      email_verified: profile?.email_verified ?? null,
      marketing_consent: profile?.marketing_consent ?? null,
      is_admin: !!roleRow
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List ArabiyaPath dialects with their levels and units. Public catalog data \u2014 useful to browse what's available before diving into a lesson.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("dialects").select(
      `id, name, levels ( id, name, order_index, units ( id, title ) )`
    );
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { dialects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-progress.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_progress_default = defineTool3({
  name: "my_progress",
  title: "My learning progress",
  description: "Return the signed-in user's recently completed ArabiyaPath lessons, with unit, level, and dialect names.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many recent lessons to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("user_progress").select(
      `lesson_id, completed_at, lessons ( title, units ( title, levels ( name, dialects ( name ) ) ) )`
    ).eq("user_id", ctx.getUserId()).order("completed_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const items = (data ?? []).map((row) => ({
      lesson_id: row.lesson_id,
      lesson_title: row.lessons?.title ?? null,
      unit_title: row.lessons?.units?.title ?? null,
      level_name: row.lessons?.units?.levels?.name ?? null,
      dialect_name: row.lessons?.units?.levels?.dialects?.name ?? null,
      completed_at: row.completed_at
    }));
    return {
      content: [
        {
          type: "text",
          text: items.length === 0 ? "No completed lessons yet." : JSON.stringify(items, null, 2)
        }
      ],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/my-purchases.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_purchases_default = defineTool4({
  name: "my_purchases",
  title: "My purchases",
  description: "Return the signed-in user's ArabiyaPath purchases (courses, bundles, memberships) with product scope and status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("purchases").select(
      `id, status, created_at, products ( name, scope, dialect_id, level_id, price )`
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const items = (data ?? []).map((row) => ({
      id: row.id,
      status: row.status,
      created_at: row.created_at,
      product_name: row.products?.name ?? null,
      scope: row.products?.scope ?? null,
      dialect_id: row.products?.dialect_id ?? null,
      level_id: row.products?.level_id ?? null,
      price: row.products?.price ?? null
    }));
    return {
      content: [
        {
          type: "text",
          text: items.length === 0 ? "No purchases on record." : JSON.stringify(items, null, 2)
        }
      ],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/my-certificates.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_certificates_default = defineTool5({
  name: "my_certificates",
  title: "My certificates",
  description: "Return the signed-in user's ArabiyaPath completion certificates with dialect, level, issue date, and public verification URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("certificates").select(
      `id, issued_at, cert_code, public_url, dialects ( name ), levels ( name )`
    ).eq("user_id", ctx.getUserId()).order("issued_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const items = (data ?? []).map((row) => ({
      id: row.id,
      issued_at: row.issued_at,
      cert_code: row.cert_code,
      public_url: row.public_url,
      dialect_name: row.dialects?.name ?? null,
      level_name: row.levels?.name ?? null
    }));
    return {
      content: [
        {
          type: "text",
          text: items.length === 0 ? "No certificates earned yet." : JSON.stringify(items, null, 2)
        }
      ],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wruizzwgevxdsaiblmsd";
var mcp_default = defineMcp({
  name: "arabiyapath-mcp",
  title: "ArabiyaPath",
  version: "0.1.0",
  instructions: "Tools for your ArabiyaPath account. Use `whoami` for profile details, `list_courses` to browse dialects/levels/units, `my_progress` for recently completed lessons, `my_purchases` for owned courses and memberships, and `my_certificates` for earned certificates. All tools act as the signed-in user; per-user data is protected by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_courses_default, my_progress_default, my_purchases_default, my_certificates_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
